### ISSUE TITLE
Administration tasks incorrect

### ISSUE THREAD

**Issue by some2** [oicr-gsi/miso-docs-oicr#67]
I use your docker container for testing purposes, I noticed that the documentation is not quite corect.

eg.

> 4.1 Add a new sequencer
> 1. Click the My Account tab at the top of the page.
> 2. Click Configure in the Sequencing Machines section.
> 3. Click the Add Sequencer link in the top right corner.
> 4. Fill in the fields of the new row that is inserted at the top of the table:
> Name: enter the serial number (case-sensitive)
> Platform: select a platform from the dropdown menu
> Hostname: enter localhost
> 5. Click Add to save the new sequencer.

should be

> 4.1 Add a new sequencer
> 1. Click Instruments in the Tracking section.
> 3. Click the Add link in the top left corner.
> 4. Fill in the fields of the new row that is inserted at the top of the table:
> Instrument Name: Name of the Instrument
> Serial Number: enter the serial number (case-sensitive)
> Platform: select a platform from the dropdown menu
> Hostname/IP Address: enter localhost
> 5. Click Add to save the new sequencer.

I also find no way to delete instruments. (Without accessing MySQL directly.)

**Comment by djcooke** [comment]
Thanks for reporting this. We will correct the documentation.

There is currently no way to delete instruments from within MISO. You would have to access MySQL to directly do this.

**Comment by callunity** [comment]
@some2 thanks for the PR!
